---
abstract: 'plugin to convert links in plain text into proper HTML <a> elements'
author:
  - 'Zoffix Znet <cpan@zoffix.com>'
build_requires:
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.012, CPAN::Meta::Converter version 2.132830'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: App-ZofCMS-Plugin-LinkifyText
requires:
  App::ZofCMS::Plugin::Base: 0
  HTML::Entities: 3.69
  URI::Escape: 3.31
  URI::Find::Schemeless: 20111103
  base: 0
  strict: 0
  warnings: 0
resources:
  bugtracker: https://github.com/zoffixznet/App-ZofCMS-Plugin-LinkifyText/issues
  repository: git://github.com/zoffixznet/App-ZofCMS-Plugin-LinkifyText.git
version: 1.001001
